### ISSUE TITLE
Docs change: "HMSET" is depreciated

### ISSUE THREAD

**Issue by jsimonrichard** [kkharji/redis-derive#4]
Just a heads up: HMSET (https://redis.io/commands/hmset/) has been depreciated in favor of HSET (https://redis.io/commands/hset/) as of Redis 4.0.0. At some point the docs should be updated, but it's not a big deal. The same command syntax should work.

**Comment by michaelvanstraten** [comment]
Sorry for taking so long to fix this. I am working on a new version, and I am thinking of yanking this version.
